name: Publish_Any_Commit
on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: |
          pnpm install
          pnpm build
          node ./scripts/prepare-package.js
          pnpm dlx pkg-pr-new publish --template ./tdesign-vue-next-demo
